[package]
name = "rilox"
version = "0.1.0"
authors = ["Alex Veber <alexveber@gmail.com>"]
edition = "2018"


[dependencies]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
# debug = true

[[test]]
name = "rilox"
path = "tests/runner.rs"
harness = false
