[package]
name = "rilox"
version = "0.1.0"
authors = ["Alex Veber <alexve@nvidia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
